import assert from "node:assert/strict";
import test from "node:test";
import { classifyRecoveryIntent, isLiveRecoveryLease, type RecoveryIntentInput } from "../src/automation/index.ts";
import type { ActionAttempt, ActionIntent, ActionReceipt, ResourceClaim } from "../src/automation/types.ts";

const intent = (overrides: Partial<ActionIntent> = {}): ActionIntent => ({ intentId: "intent-r1", projectId: "project-r1", stageSpecId: null, stepSpecId: null, attemptId: null, actionType: "WEBGPT_TEST_ACTION", targetRef: "opaque:target", sideEffectClass: "RECONCILABLE", payloadRef: "artifact:payload", payloadHash: "payload-hash", executionOptions: {}, semanticSha256: "semantic-r1", idempotencyRef: "idempotency-r1", expectedOutcomeRef: null, policyVersionId: "policy-v1", state: "DISPATCHING", createdAt: "2026-08-23T00:00:00.000Z", ...overrides });
const attempt = (overrides: Partial<ActionAttempt> = {}): ActionAttempt => ({ actionAttemptId: "attempt-r1", intentId: "intent-r1", dispatchNumber: 1, state: "RUNNING", startedAt: "2026-08-23T00:00:01.000Z", completedAt: null, executorRef: "review-harness", recoveryState: "IN_PROGRESS", policyVersionId: "policy-v1", providerRequestRef: "provider-ref-1", providerObservationRef: null, providerSemanticSha256: "semantic-r1", ...overrides });
const receipt = (overrides: Partial<ActionReceipt> = {}): ActionReceipt => ({ receiptId: "receipt-r1", actionAttemptId: "attempt-r1", status: "UNKNOWN", externalStatus: "ACCEPTED_UNKNOWN_RESULT", exitCode: null, resultHash: null, externalRefs: ["provider-ref-1"], createdAt: "2026-08-23T00:00:02.000Z", reconcileState: "RECOVERY_REQUIRED", provider: "TEST_PROVIDER", providerRequestRef: "provider-ref-1", providerObservationRef: null, outcomeCertainty: "ACCEPTED_UNKNOWN_RESULT", evidenceRefs: [], ...overrides });
const claim = (overrides: Partial<ResourceClaim> = {}): ResourceClaim => ({ resourceClaimId: "claim-r1", projectId: "project-r1", resourceType: "WEBGPT_BROWSER", resourceKey: "webgpt:browser:singleton", mode: "EXCLUSIVE", state: "ACQUIRED", requestedAt: "2026-08-23T00:00:01.000Z", acquiredAt: "2026-08-23T00:00:01.000Z", releasedAt: null, ownerAttemptId: "attempt-r1", resourceLeaseRef: "lease-r1", leaseEpoch: 1, ...overrides });

test("pre-submit recovery resumes local preparation without authorizing prompt replay", () => {
  const result = classifyRecoveryIntent({ intent: intent(), attempt: attempt({ state: "CREATED", startedAt: null, recoveryState: "KNOWN_NOT_STARTED", providerRequestRef: null }), resourceClaim: claim({ state: "REQUESTED", acquiredAt: null, resourceLeaseRef: null }) });
  assert.equal(result.disposition, "SAFE_TO_RESUME_LOCAL"); assert.equal(result.providerSubmitAllowed, true); assert.equal(result.blindResendAllowed, false);
});
test("UNKNOWN provider request reattaches the same correlation and never creates a new attempt", () => {
  const result = classifyRecoveryIntent({ intent: intent({ state: "UNCERTAIN" }), attempt: attempt({ state: "UNCERTAIN", recoveryState: "RECOVERY_REQUIRED" }), receipt: receipt(), providerRequest: { externalRefId: "provider-ref-1", opaqueId: "opaque-provider-1", state: "UNKNOWN" }, resourceClaim: claim() });
  assert.equal(result.disposition, "REATTACH_PROVIDER_REQUEST"); assert.equal(result.providerRequestRef, "provider-ref-1"); assert.equal(result.requiresExistingAttempt, true); assert.equal(result.providerSubmitAllowed, false);
});
test("started attempt without provider correlation is recovery-only", () => { const result = classifyRecoveryIntent({ intent: intent(), attempt: attempt({ providerRequestRef: null }), resourceClaim: claim() }); assert.equal(result.disposition, "RECONCILE_REQUIRED"); assert.equal(result.providerSubmitAllowed, false); });
test("terminal receipt remains terminal after restart", () => { const result = classifyRecoveryIntent({ intent: intent({ state: "COMPLETED" }), attempt: attempt({ state: "COMPLETED", recoveryState: "COMPLETED" }), receipt: receipt({ status: "SUCCEEDED", reconcileState: "NOT_REQUIRED", outcomeCertainty: "TERMINAL_CONFIRMED" }), providerRequest: { externalRefId: "provider-ref-1", opaqueId: "opaque-provider-1", state: "COMPLETED" }, resourceClaim: claim({ state: "RELEASED" }) }); assert.equal(result.disposition, "TERMINAL"); assert.equal(result.nextAction, "NONE"); });
test("historical ResourceClaim does not imply a live BUSY lease", () => { const result = classifyRecoveryIntent({ intent: intent({ state: "UNCERTAIN" }), attempt: attempt({ state: "UNCERTAIN", recoveryState: "RECOVERY_REQUIRED" }), receipt: receipt(), providerRequest: { externalRefId: "provider-ref-1", opaqueId: "opaque-provider-1", state: "UNKNOWN" }, resourceClaim: claim(), liveLease: null }); assert.equal(result.disposition, "REATTACH_PROVIDER_REQUEST"); assert.equal(result.historicalResourceClaim, true); assert.equal(isLiveRecoveryLease(null), false); });
test("a live lease owned by another attempt blocks recovery", () => { const result = classifyRecoveryIntent({ intent: intent({ state: "UNCERTAIN" }), attempt: attempt({ state: "UNCERTAIN", recoveryState: "RECOVERY_REQUIRED" }), receipt: receipt(), providerRequest: { externalRefId: "provider-ref-1", opaqueId: "opaque-provider-1", state: "UNKNOWN" }, liveLease: { active: true, ownerAttemptId: "other-attempt" } }); assert.equal(result.disposition, "RESOURCE_BUSY"); assert.equal(result.providerSubmitAllowed, false); });
test("pinned PolicyVersion survives latest-policy drift", () => { const result = classifyRecoveryIntent({ intent: intent({ state: "UNCERTAIN" }), attempt: attempt({ state: "UNCERTAIN", recoveryState: "RECOVERY_REQUIRED" }), receipt: receipt(), providerRequest: { externalRefId: "provider-ref-1", opaqueId: "opaque-provider-1", state: "UNKNOWN" }, currentPolicyVersionId: "policy-v2" }); assert.equal(result.policyVersionId, "policy-v1"); assert.equal(result.policyVersionDrift, true); });
test("legacy side-effecting record without a policy pin fails closed", () => { const result = classifyRecoveryIntent({ intent: intent({ policyVersionId: null, state: "UNCERTAIN" }), attempt: attempt({ policyVersionId: null, state: "UNCERTAIN", recoveryState: "RECOVERY_REQUIRED" }), receipt: receipt() }); assert.equal(result.disposition, "POLICY_PIN_REQUIRED"); assert.equal(result.providerSubmitAllowed, false); });
test("correlation mismatch is corrupt", () => { const result = classifyRecoveryIntent({ intent: intent({ state: "UNCERTAIN" }), attempt: attempt({ state: "UNCERTAIN", recoveryState: "RECOVERY_REQUIRED" }), receipt: receipt({ providerRequestRef: "provider-ref-other" }), providerRequest: { externalRefId: "provider-ref-1", opaqueId: "opaque-provider-1", state: "UNKNOWN" } }); assert.equal(result.disposition, "CORRUPT"); assert.equal(result.blindResendAllowed, false); });
test("recovery decision contains no raw PromptRecovery payload", () => { const result = classifyRecoveryIntent({ intent: intent({ state: "UNCERTAIN" }), attempt: attempt({ state: "UNCERTAIN", recoveryState: "RECOVERY_REQUIRED" }), receipt: receipt(), providerRequest: { externalRefId: "provider-ref-1", opaqueId: "opaque-provider-1", state: "UNKNOWN" } }); assert.equal(result.blindResendAllowed, false); assert.doesNotMatch(JSON.stringify(result), /prompt|transcript|cookie|token/i); });
