import assert from "node:assert/strict";
import { access, mkdtemp, rm, utimes, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { assertIntentAttemptPolicyPin, assertProviderCorrelationIdentity, assertStableIdentityPreserved, createEmptyAutomationDocument, createSqlitePersistence, inspectExistingSqliteAutomationFile, recoverInterruptedMigration, StableIdentityValidationError } from "../src/automation/index.ts";

test("migration recovery skips a corrupt newest candidate and promotes the newest older valid candidate", async () => {
  const root = await mkdtemp(join(tmpdir(), "arch-v2-8-fix06-candidate-fallback-")); const filePath = join(root, "automation.db"); const older = `${filePath}.migration-001.sqlite`; const newest = `${filePath}.migration-002.sqlite`; const sourceBackup = `${filePath}.v2-backup-001.json`;
  try { const persistence = await createSqlitePersistence(older); const empty = createEmptyAutomationDocument(); persistence.replaceDocument(empty, empty); persistence.close(); await writeFile(sourceBackup, JSON.stringify(empty), "utf8"); await writeFile(newest, "not-a-sqlite-database", "utf8"); await utimes(older, new Date("2026-08-23T00:00:01.000Z"), new Date("2026-08-23T00:00:01.000Z")); await utimes(newest, new Date("2026-08-23T00:00:02.000Z"), new Date("2026-08-23T00:00:02.000Z")); await recoverInterruptedMigration(filePath); assert.equal((await inspectExistingSqliteAutomationFile(filePath)).status, "valid"); assert.equal((await inspectExistingSqliteAutomationFile(newest)).status, "invalid"); } finally { await rm(root, { recursive: true, force: true }); }
});
test("migration recovery fails closed when every candidate is corrupt and leaves evidence intact", async () => {
  const root = await mkdtemp(join(tmpdir(), "arch-v2-8-fix06-candidate-fail-")); const filePath = join(root, "automation.db"); const candidate = `${filePath}.migration-001.sqlite`;
  try { await writeFile(candidate, "corrupt", "utf8"); await assert.rejects(() => recoverInterruptedMigration(filePath), /no valid candidate.*CORRUPT/i); await assert.rejects(() => access(filePath)); await assert.doesNotReject(() => access(candidate)); } finally { await rm(root, { recursive: true, force: true }); }
});
test("stable identity validator covers the migration/provider identity set", () => {
  const before = { projectId: "project-1", requirementVersionId: "requirement-1", planVersionId: "plan-1", stageId: "stage-1", stepId: "step-1", actionIntentId: "intent-1", actionAttemptId: "attempt-1", nativeThreadId: "native-thread-1", providerTargetRef: "provider-target-1", providerRequestRef: "provider-request-1", providerObservationRef: "provider-observation-1", idempotencyRef: "idem-1", semanticRef: "semantic-1", policyVersionId: "policy-1" };
  assertStableIdentityPreserved(before, { ...before }); assert.throws(() => assertStableIdentityPreserved(before, { ...before, semanticRef: "semantic-drift" }), (error: unknown) => error instanceof StableIdentityValidationError && error.field === "semanticRef"); assertIntentAttemptPolicyPin({ policyVersionId: "policy-1" }, { policyVersionId: "policy-1" }); assert.throws(() => assertIntentAttemptPolicyPin({ policyVersionId: "policy-1" }, { policyVersionId: "policy-2" }), (error: unknown) => error instanceof StableIdentityValidationError && error.code === "ACTION_POLICY_PIN_MISMATCH"); assertProviderCorrelationIdentity({ actionIntentId: "intent-1", actionAttemptId: "attempt-1", policyVersionId: "policy-1", idempotencyRef: "idem-1", semanticRef: "semantic-1", providerTargetRef: "provider-target-1", providerRequest: { providerRequestRef: "provider-request-1", providerTargetRef: "provider-target-1", idempotencyRef: "idem-1", semanticRef: "semantic-1", policyVersionId: "policy-1" }, requestExternalRef: { externalRefId: "external-request-1", kind: "WEBGPT_PROVIDER_REQUEST", opaqueId: "provider-request-1" }, observationExternalRef: { externalRefId: "external-observation-1", kind: "WEBGPT_PROVIDER_OBSERVATION", opaqueId: "provider-request-1" } }); assert.throws(() => assertProviderCorrelationIdentity({ actionIntentId: "intent-1", actionAttemptId: "attempt-1", policyVersionId: "policy-1", idempotencyRef: "idem-1", semanticRef: "semantic-1", providerRequest: { providerRequestRef: "provider-request-1" }, requestExternalRef: { externalRefId: "external-request-1", kind: "WEBGPT_PROVIDER_OBSERVATION", opaqueId: "provider-request-1" } }), (error: unknown) => error instanceof StableIdentityValidationError && error.code === "PROVIDER_EXTERNAL_REF_MISMATCH");
});
