const { contextBridge, ipcRenderer } = require("electron");

const channels = Object.freeze({
  state: "native-runtime:state",
  start: "native-runtime:start",
  resume: "native-runtime:resume",
  read: "native-runtime:read",
  turn: "native-runtime:turn",
  turnResult: "native-runtime:turn-result",
  composerCapabilities: "native-runtime:composer-capabilities",
  composerRequest: "native-runtime:composer-request",
  composerPreferencesGet: "persistence:composer-preferences:get",
  composerPreferencesSave: "persistence:composer-preferences:save",
  interrupt: "native-runtime:interrupt",
  close: "native-runtime:close",
  persistenceInspect: "persistence:inspect",
  projectList: "persistence:projects:list",
  projectCreate: "persistence:projects:create",
  projectChooseDirectory: "persistence:projects:choose-directory",
  projectUpdate: "persistence:projects:update",
  projectRemove: "persistence:projects:remove",
  projectOpen: "persistence:projects:open",
  threadList: "persistence:threads:list",
  threadBind: "persistence:threads:bind",
  threadUpdate: "persistence:threads:update",
  threadCreate: "native-thread:create",
  threadSwitch: "native-thread:switch",
  event: "native-runtime:event",
  serverRequest: "native-runtime:server-request",
  serverRequestResponse: "native-runtime:server-request-response",
  mapStatus: "map:status",
  mapEnable: "map:enable",
  mapPause: "map:pause",
  mapResume: "map:resume",
  mapState: "map:state",
  projectMapStatus: "project-map:status",
  projectMapEnable: "project-map:enable",
  projectMapPause: "project-map:pause",
  projectMapResume: "project-map:resume",
  projectMapUpdate: "project-map:update",
  projectMapMaintenanceRead: "project-map:maintenance-read",
  projectMapState: "project-map:state",
});

function listen(channel: string, listener: (payload: unknown) => void): () => void {
  const handler = (_event: unknown, payload: unknown) => listener(payload);
  ipcRenderer.on(channel, handler);
  return () => ipcRenderer.removeListener(channel, handler);
}

contextBridge.exposeInMainWorld("codexWorkbenchV1", Object.freeze({
  getState: () => ipcRenderer.invoke(channels.state),
  inspectPersistence: () => ipcRenderer.invoke(channels.persistenceInspect),
  listProjects: () => ipcRenderer.invoke(channels.projectList),
  createProject: (input: unknown) => ipcRenderer.invoke(channels.projectCreate, input),
  chooseProjectDirectory: () => ipcRenderer.invoke(channels.projectChooseDirectory),
  updateProject: (projectId: string, patch: unknown) => ipcRenderer.invoke(channels.projectUpdate, String(projectId ?? "").slice(0, 256), patch),
  removeProject: (projectId: string) => ipcRenderer.invoke(channels.projectRemove, String(projectId ?? "").slice(0, 256)),
  openProject: (projectId: string) => ipcRenderer.invoke(channels.projectOpen, String(projectId ?? "").slice(0, 256)),
  listThreads: (projectId?: string | null) => ipcRenderer.invoke(channels.threadList, projectId),
  bindThreadToProject: (nativeThreadId: string, projectId: string | null) => ipcRenderer.invoke(channels.threadBind, String(nativeThreadId ?? "").slice(0, 256), projectId),
  updateThreadProjection: (nativeThreadId: string, patch: unknown) => ipcRenderer.invoke(channels.threadUpdate, String(nativeThreadId ?? "").slice(0, 256), patch),
  createThread: (projectId: string | null) => ipcRenderer.invoke(channels.threadCreate, projectId),
  switchThread: (nativeThreadId: string) => ipcRenderer.invoke(channels.threadSwitch, String(nativeThreadId ?? "").slice(0, 256)),
  startThread: () => ipcRenderer.invoke(channels.start),
  resumeThread: (nativeThreadId: string) => ipcRenderer.invoke(channels.resume, String(nativeThreadId ?? "").slice(0, 256)),
  readThread: () => ipcRenderer.invoke(channels.read),
  startTurn: (prompt: string, nativeThreadId: string, preferences: unknown) => ipcRenderer.invoke(channels.turn, String(prompt ?? ""), String(nativeThreadId ?? "").slice(0, 256), preferences),
  getComposerCapabilities: (nativeThreadId: string) => ipcRenderer.invoke(channels.composerCapabilities, String(nativeThreadId ?? "").slice(0, 256)),
  getComposerPreferences: (nativeThreadId: string) => ipcRenderer.invoke(channels.composerPreferencesGet, String(nativeThreadId ?? "").slice(0, 256)),
  saveComposerPreferences: (nativeThreadId: string, preferences: unknown) => ipcRenderer.invoke(channels.composerPreferencesSave, String(nativeThreadId ?? "").slice(0, 256), preferences),
  interruptTurn: (nativeThreadId?: string | null) => ipcRenderer.invoke(channels.interrupt, nativeThreadId ? String(nativeThreadId).slice(0, 256) : null),
  respondToServerRequest: (nativeThreadId: string, requestId: string | number, response: unknown) => ipcRenderer.invoke(channels.serverRequestResponse, String(nativeThreadId ?? "").slice(0, 256), requestId, response),
  getMapStatus: (nativeThreadId?: string) => ipcRenderer.invoke(channels.mapStatus, nativeThreadId ? String(nativeThreadId).slice(0, 256) : undefined),
  enableMap: (nativeThreadId?: string) => ipcRenderer.invoke(channels.mapEnable, nativeThreadId ? String(nativeThreadId).slice(0, 256) : undefined),
  pauseMap: (nativeThreadId?: string) => ipcRenderer.invoke(channels.mapPause, nativeThreadId ? String(nativeThreadId).slice(0, 256) : undefined),
  resumeMap: (nativeThreadId?: string) => ipcRenderer.invoke(channels.mapResume, nativeThreadId ? String(nativeThreadId).slice(0, 256) : undefined),
  getProjectMapStatus: (projectId: string) => ipcRenderer.invoke(channels.projectMapStatus, String(projectId ?? "").slice(0, 256)),
  enableProjectMap: (projectId: string) => ipcRenderer.invoke(channels.projectMapEnable, String(projectId ?? "").slice(0, 256)),
  pauseProjectMap: (projectId: string) => ipcRenderer.invoke(channels.projectMapPause, String(projectId ?? "").slice(0, 256)),
  resumeProjectMap: (projectId: string) => ipcRenderer.invoke(channels.projectMapResume, String(projectId ?? "").slice(0, 256)),
  updateProjectMap: (projectId: string, delta: unknown) => ipcRenderer.invoke(channels.projectMapUpdate, String(projectId ?? "").slice(0, 256), delta),
  getProjectMapMaintenance: (projectId: string) => ipcRenderer.invoke(channels.projectMapMaintenanceRead, String(projectId ?? "").slice(0, 256)),
  closeRuntime: () => ipcRenderer.invoke(channels.close),
  onEvent: (listener: (payload: unknown) => void) => listen(channels.event, listener),
  onServerRequest: (listener: (payload: unknown) => void) => listen(channels.serverRequest, listener),
  onComposerRequest: (listener: (payload: unknown) => void) => listen(channels.composerRequest, listener),
  onTurnResult: (listener: (payload: unknown) => void) => listen(channels.turnResult, listener),
  onState: (listener: (payload: unknown) => void) => listen(channels.state, listener),
  onMapState: (listener: (payload: unknown) => void) => listen(channels.mapState, listener),
  onProjectMapState: (listener: (payload: unknown) => void) => listen(channels.projectMapState, listener),
}));
