const { contextBridge, ipcRenderer } = require("electron");

const channels = Object.freeze({
  state: "native-runtime:state",
  start: "native-runtime:start",
  resume: "native-runtime:resume",
  read: "native-runtime:read",
  turn: "native-runtime:turn",
  turnResult: "native-runtime:turn-result",
  composerCapabilities: "native-runtime:composer-capabilities",
  composerRequest: "native-runtime:composer-request",
  composerPreferencesGet: "persistence:composer-preferences:get",
  composerPreferencesSave: "persistence:composer-preferences:save",
  interrupt: "native-runtime:interrupt",
  close: "native-runtime:close",
  persistenceInspect: "persistence:inspect",
  projectList: "persistence:projects:list",
  projectCreate: "persistence:projects:create",
  projectChooseDirectory: "persistence:projects:choose-directory",
  projectUpdate: "persistence:projects:update",
  projectRemove: "persistence:projects:remove",
  projectOpen: "persistence:projects:open",
  projectAutomationAssociationList: "persistence:project-automation-associations:list",
  projectAutomationCandidateList: "automation:projects:association-candidates",
  automationProjectCreate: "automation:project:create",
  projectAutomationBind: "persistence:project-automation-associations:bind",
  projectAutomationUnlink: "persistence:project-automation-associations:unlink",
  automationRequirementStart: "automation:requirement:start",
  automationRequirementDraft: "automation:requirement:draft",
  automationRequirementReconcile: "automation:requirement:reconcile",
  automationRequirementInspect: "automation:requirement:inspect",
  automationRequirementAnswer: "automation:requirement:answer",
  automationRequirementConfirm: "automation:requirement:confirm",
  automationPlannerCreate: "automation:planner:create",
  automationPlannerReconcile: "automation:planner:reconcile",
  automationPlannerRetry: "automation:planner:retry",
  automationPlannerStatus: "automation:planner:status",
  automationPlannerResult: "automation:planner:result",
  automationStepExecute: "automation:step:execute",
  automationStepReconcile: "automation:step:reconcile",
  automationStepVerify: "automation:step:verify",
  automationStepReview: "automation:step:review",
  automationStageGate: "automation:stage:gate",
  automationStageAdvance: "automation:stage:advance",
  automationProjectGovernance: "automation:project:governance",
  automationProjectComplete: "automation:project:complete",
  threadList: "persistence:threads:list",
  threadBind: "persistence:threads:bind",
  threadUpdate: "persistence:threads:update",
  threadCreate: "native-thread:create",
  threadSwitch: "native-thread:switch",
  event: "native-runtime:event",
  serverRequest: "native-runtime:server-request",
  serverRequestResponse: "native-runtime:server-request-response",
  mapStatus: "map:status",
  mapEnable: "map:enable",
  mapPause: "map:pause",
  mapResume: "map:resume",
  mapState: "map:state",
  projectMapStatus: "project-map:status",
  projectMapGovernanceReferences: "project-map:governance-references",
  projectMapEnable: "project-map:enable",
  projectMapPause: "project-map:pause",
  projectMapResume: "project-map:resume",
  projectMapUpdate: "project-map:update",
  projectMapMaintenanceRead: "project-map:maintenance-read",
  projectMapState: "project-map:state",
  webGptState: "webgpt:state",
  webGptRequestState: "webgpt:request-state",
  webGptOpenRequest: "webgpt:open-request",
  webGptOpenWorkspace: "webgpt:open-workspace",
  webGptOpenHome: "webgpt:open-home",
  webGptOpenChat: "webgpt:open-chat",
  webGptRoleList: "webgpt:role-list",
  webGptRoleOpen: "webgpt:role-open",
  webGptBounds: "webgpt:bounds",
  webGptVisible: "webgpt:visible",
  webGptCurrentUrl: "webgpt:current-url",
  webGptPageState: "webgpt:page-state",
  webGptScreenshot: "webgpt:screenshot",
  webGptRequestUserControl: "webgpt:request-user-control",
  webGptReturnAutomationControl: "webgpt:return-automation-control",
  webGptPause: "webgpt:pause",
  webGptHealth: "webgpt:health",
  webGptBack: "webgpt:back",
  webGptForward: "webgpt:forward",
  webGptReload: "webgpt:reload",
  webGptOpenExternal: "webgpt:open-external",
});

function listen(channel: string, listener: (payload: unknown) => void): () => void {
  const handler = (_event: unknown, payload: unknown) => listener(payload);
  ipcRenderer.on(channel, handler);
  return () => ipcRenderer.removeListener(channel, handler);
}

contextBridge.exposeInMainWorld("codexWorkbenchV1", Object.freeze({
  getState: () => ipcRenderer.invoke(channels.state),
  inspectPersistence: () => ipcRenderer.invoke(channels.persistenceInspect),
  listProjects: () => ipcRenderer.invoke(channels.projectList),
  createProject: (input: unknown) => ipcRenderer.invoke(channels.projectCreate, input),
  chooseProjectDirectory: () => ipcRenderer.invoke(channels.projectChooseDirectory),
  updateProject: (projectId: string, patch: unknown) => ipcRenderer.invoke(channels.projectUpdate, String(projectId ?? "").slice(0, 256), patch),
  removeProject: (projectId: string) => ipcRenderer.invoke(channels.projectRemove, String(projectId ?? "").slice(0, 256)),
  openProject: (projectId: string) => ipcRenderer.invoke(channels.projectOpen, String(projectId ?? "").slice(0, 256)),
  listProjectAutomationAssociations: (productProjectId: string) => ipcRenderer.invoke(channels.projectAutomationAssociationList, String(productProjectId ?? "").slice(0, 256)),
  listAutomationProjectsForAssociation: () => ipcRenderer.invoke(channels.projectAutomationCandidateList),
  createAutomationProject: (name: string) => ipcRenderer.invoke(channels.automationProjectCreate, String(name ?? "").slice(0, 256)),
  bindAutomationProject: (productProjectId: string, automationProjectId: string) => ipcRenderer.invoke(channels.projectAutomationBind, String(productProjectId ?? "").slice(0, 256), String(automationProjectId ?? "").slice(0, 256)),
  unlinkAutomationProject: (productProjectId: string, automationProjectId: string) => ipcRenderer.invoke(channels.projectAutomationUnlink, String(productProjectId ?? "").slice(0, 256), String(automationProjectId ?? "").slice(0, 256)),
  startAutomationRequirement: (projectId: string, goal: string, providerTargetRef: string) => ipcRenderer.invoke(channels.automationRequirementStart, String(projectId ?? "").slice(0, 256), String(goal ?? "").slice(0, 4_096), String(providerTargetRef ?? "").slice(0, 384)),
  requestAutomationRequirementDraft: (sessionId: string) => ipcRenderer.invoke(channels.automationRequirementDraft, String(sessionId ?? "").slice(0, 256)),
  reconcileAutomationRequirement: (sessionId: string, roundId?: string | null) => ipcRenderer.invoke(channels.automationRequirementReconcile, String(sessionId ?? "").slice(0, 256), roundId == null ? undefined : String(roundId).slice(0, 256)),
  getAutomationRequirementProject: (projectId: string) => ipcRenderer.invoke(channels.automationRequirementInspect, String(projectId ?? "").slice(0, 256)),
  answerAutomationRequirementQuestions: (sessionId: string, roundId: string | null | undefined, answers: unknown) => ipcRenderer.invoke(channels.automationRequirementAnswer, String(sessionId ?? "").slice(0, 256), roundId == null ? undefined : String(roundId).slice(0, 256), answers),
  confirmAutomationRequirement: (projectId: string, requirementVersionId: string, expectedPayloadSha256: string) => ipcRenderer.invoke(channels.automationRequirementConfirm, String(projectId ?? "").slice(0, 256), String(requirementVersionId ?? "").slice(0, 256), String(expectedPayloadSha256 ?? "").slice(0, 64)),
  createAutomationPlan: (projectId: string, providerTargetRef: string, requirementVersionId?: string | null) => ipcRenderer.invoke(channels.automationPlannerCreate, String(projectId ?? "").slice(0, 256), String(providerTargetRef ?? "").slice(0, 2_000), requirementVersionId == null ? undefined : String(requirementVersionId).slice(0, 256)),
  reconcileAutomationPlan: (projectId: string, actionAttemptId: string) => ipcRenderer.invoke(channels.automationPlannerReconcile, String(projectId ?? "").slice(0, 256), String(actionAttemptId ?? "").slice(0, 256)),
  retryAutomationPlan: (projectId: string, actionIntentId: string) => ipcRenderer.invoke(channels.automationPlannerRetry, String(projectId ?? "").slice(0, 256), String(actionIntentId ?? "").slice(0, 256)),
  getAutomationPlannerStatus: (projectId: string, actionIntentId: string) => ipcRenderer.invoke(channels.automationPlannerStatus, String(projectId ?? "").slice(0, 256), String(actionIntentId ?? "").slice(0, 256)),
  getAutomationPlannerResult: (projectId: string, actionIntentId: string) => ipcRenderer.invoke(channels.automationPlannerResult, String(projectId ?? "").slice(0, 256), String(actionIntentId ?? "").slice(0, 256)),
  executeAutomationStep: (projectId: string, stepSpecId: string, providerTargetRef: string, userConfirmedSideEffect = false) => ipcRenderer.invoke(channels.automationStepExecute, String(projectId ?? "").slice(0, 256), String(stepSpecId ?? "").slice(0, 256), String(providerTargetRef ?? "").slice(0, 512), userConfirmedSideEffect === true),
  reconcileAutomationStep: (projectId: string, executionAttemptId: string) => ipcRenderer.invoke(channels.automationStepReconcile, String(projectId ?? "").slice(0, 256), String(executionAttemptId ?? "").slice(0, 256)),
  verifyAutomationStep: (projectId: string, executionAttemptId: string) => ipcRenderer.invoke(channels.automationStepVerify, String(projectId ?? "").slice(0, 256), String(executionAttemptId ?? "").slice(0, 256)),
  reviewAutomationStep: (projectId: string, executionAttemptId: string, decision: string, reviewerRef?: string | null) => ipcRenderer.invoke(channels.automationStepReview, String(projectId ?? "").slice(0, 256), String(executionAttemptId ?? "").slice(0, 256), String(decision ?? "").slice(0, 16), reviewerRef == null ? undefined : String(reviewerRef).slice(0, 256)),
  gateAutomationStage: (projectId: string, stageSpecId: string, decision: string, gatekeeperRef?: string | null) => ipcRenderer.invoke(channels.automationStageGate, String(projectId ?? "").slice(0, 256), String(stageSpecId ?? "").slice(0, 256), String(decision ?? "").slice(0, 16), gatekeeperRef == null ? undefined : String(gatekeeperRef).slice(0, 256)),
  advanceAutomationStage: (projectId: string, stageSpecId: string) => ipcRenderer.invoke(channels.automationStageAdvance, String(projectId ?? "").slice(0, 256), String(stageSpecId ?? "").slice(0, 256)),
  getAutomationGovernanceProject: (projectId: string) => ipcRenderer.invoke(channels.automationProjectGovernance, String(projectId ?? "").slice(0, 256)),
  completeAutomationProject: (projectId: string) => ipcRenderer.invoke(channels.automationProjectComplete, String(projectId ?? "").slice(0, 256)),
  listThreads: (projectId?: string | null) => ipcRenderer.invoke(channels.threadList, projectId),
  bindThreadToProject: (nativeThreadId: string, projectId: string | null) => ipcRenderer.invoke(channels.threadBind, String(nativeThreadId ?? "").slice(0, 256), projectId),
  updateThreadProjection: (nativeThreadId: string, patch: unknown) => ipcRenderer.invoke(channels.threadUpdate, String(nativeThreadId ?? "").slice(0, 256), patch),
  createThread: (projectId: string | null) => ipcRenderer.invoke(channels.threadCreate, projectId),
  switchThread: (nativeThreadId: string) => ipcRenderer.invoke(channels.threadSwitch, String(nativeThreadId ?? "").slice(0, 256)),
  startThread: () => ipcRenderer.invoke(channels.start),
  resumeThread: (nativeThreadId: string) => ipcRenderer.invoke(channels.resume, String(nativeThreadId ?? "").slice(0, 256)),
  readThread: () => ipcRenderer.invoke(channels.read),
  startTurn: (prompt: string, nativeThreadId: string, preferences: unknown) => ipcRenderer.invoke(channels.turn, String(prompt ?? ""), String(nativeThreadId ?? "").slice(0, 256), preferences),
  getComposerCapabilities: (nativeThreadId: string) => ipcRenderer.invoke(channels.composerCapabilities, String(nativeThreadId ?? "").slice(0, 256)),
  getComposerPreferences: (nativeThreadId: string) => ipcRenderer.invoke(channels.composerPreferencesGet, String(nativeThreadId ?? "").slice(0, 256)),
  saveComposerPreferences: (nativeThreadId: string, preferences: unknown) => ipcRenderer.invoke(channels.composerPreferencesSave, String(nativeThreadId ?? "").slice(0, 256), preferences),
  interruptTurn: (nativeThreadId?: string | null) => ipcRenderer.invoke(channels.interrupt, nativeThreadId ? String(nativeThreadId).slice(0, 256) : null),
  respondToServerRequest: (nativeThreadId: string, requestId: string | number, response: unknown) => ipcRenderer.invoke(channels.serverRequestResponse, String(nativeThreadId ?? "").slice(0, 256), requestId, response),
  getMapStatus: (nativeThreadId?: string) => ipcRenderer.invoke(channels.mapStatus, nativeThreadId ? String(nativeThreadId).slice(0, 256) : undefined),
  enableMap: (nativeThreadId?: string) => ipcRenderer.invoke(channels.mapEnable, nativeThreadId ? String(nativeThreadId).slice(0, 256) : undefined),
  pauseMap: (nativeThreadId?: string) => ipcRenderer.invoke(channels.mapPause, nativeThreadId ? String(nativeThreadId).slice(0, 256) : undefined),
  resumeMap: (nativeThreadId?: string) => ipcRenderer.invoke(channels.mapResume, nativeThreadId ? String(nativeThreadId).slice(0, 256) : undefined),
  getProjectMapStatus: (projectId: string) => ipcRenderer.invoke(channels.projectMapStatus, String(projectId ?? "").slice(0, 256)),
  getProjectMapGovernanceReferences: (projectId: string) => ipcRenderer.invoke(channels.projectMapGovernanceReferences, String(projectId ?? "").slice(0, 256)),
  enableProjectMap: (projectId: string) => ipcRenderer.invoke(channels.projectMapEnable, String(projectId ?? "").slice(0, 256)),
  pauseProjectMap: (projectId: string) => ipcRenderer.invoke(channels.projectMapPause, String(projectId ?? "").slice(0, 256)),
  resumeProjectMap: (projectId: string) => ipcRenderer.invoke(channels.projectMapResume, String(projectId ?? "").slice(0, 256)),
  updateProjectMap: (projectId: string, delta: unknown) => ipcRenderer.invoke(channels.projectMapUpdate, String(projectId ?? "").slice(0, 256), delta),
  getProjectMapMaintenance: (projectId: string) => ipcRenderer.invoke(channels.projectMapMaintenanceRead, String(projectId ?? "").slice(0, 256)),
  closeRuntime: () => ipcRenderer.invoke(channels.close),
  onEvent: (listener: (payload: unknown) => void) => listen(channels.event, listener),
  onServerRequest: (listener: (payload: unknown) => void) => listen(channels.serverRequest, listener),
  onComposerRequest: (listener: (payload: unknown) => void) => listen(channels.composerRequest, listener),
  onTurnResult: (listener: (payload: unknown) => void) => listen(channels.turnResult, listener),
  onState: (listener: (payload: unknown) => void) => listen(channels.state, listener),
  onMapState: (listener: (payload: unknown) => void) => listen(channels.mapState, listener),
  onProjectMapState: (listener: (payload: unknown) => void) => listen(channels.projectMapState, listener),
}));

contextBridge.exposeInMainWorld("codexWorkbenchWebGPT", Object.freeze({
  openWebGptWorkspace: () => ipcRenderer.invoke(channels.webGptOpenWorkspace),
  openWebGptHome: () => ipcRenderer.invoke(channels.webGptOpenHome),
  openWebGptChat: (url: string) => ipcRenderer.invoke(channels.webGptOpenChat, String(url ?? "").slice(0, 2_000)),
  listWebGptRoles: (projectId: string) => ipcRenderer.invoke(channels.webGptRoleList, String(projectId ?? "").slice(0, 256)),
  openWebGptRole: (projectId: string, role: string) => ipcRenderer.invoke(channels.webGptRoleOpen, String(projectId ?? "").slice(0, 256), String(role ?? "").slice(0, 32)),
  setWebGptBounds: (bounds: unknown) => ipcRenderer.invoke(channels.webGptBounds, bounds),
  setWebGptVisible: (visible: boolean) => ipcRenderer.invoke(channels.webGptVisible, visible === true),
  getWebGptCurrentUrl: () => ipcRenderer.invoke(channels.webGptCurrentUrl),
  getWebGptPageState: () => ipcRenderer.invoke(channels.webGptPageState),
  takeWebGptScreenshot: () => ipcRenderer.invoke(channels.webGptScreenshot),
  requestWebGptUserControl: () => ipcRenderer.invoke(channels.webGptRequestUserControl),
  returnWebGptAutomationControl: () => ipcRenderer.invoke(channels.webGptReturnAutomationControl),
  pauseWebGpt: () => ipcRenderer.invoke(channels.webGptPause),
  getWebGptHealth: () => ipcRenderer.invoke(channels.webGptHealth),
  webGptBack: () => ipcRenderer.invoke(channels.webGptBack),
  webGptForward: () => ipcRenderer.invoke(channels.webGptForward),
  reloadWebGpt: () => ipcRenderer.invoke(channels.webGptReload),
  openWebGptExternal: () => ipcRenderer.invoke(channels.webGptOpenExternal),
  onWebGptState: (listener: (payload: unknown) => void) => listen(channels.webGptState, listener),
  onWebGptRequestState: (listener: (payload: unknown) => void) => listen(channels.webGptRequestState, listener),
  onWebGptOpenRequest: (listener: () => void) => listen(channels.webGptOpenRequest, () => listener()),
}));
